---
- name: creating users and creating files in users home directory
  hosts: all
  tasks:
   - name: creating user
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: creating files in user home dir
     file:
      name: "{{d}}"
      state: "{{e}}"
...
